"""
Constants - config-like values
TODO: consider making this a config file proper
"""

import os

DEV = os.getenv("TTS_AUDIOBOOK_TOOL_DEV", "").lower() in ("true", "1", "yes") and True

PROJECT_DEFAULT_LANGUAGE = "en"
PROJECT_DEFAULT_SECTION_SOUND_EFFECT = False
PROJECT_DEFAULT_REALTIME_SAVE = False

PROJECT_MAX_RETRIES_DEFAULT = 1
PROJECT_MAX_RETRIES_MIN = 1
PROJECT_MAX_RETRIES_MAX = 3

PREFS_DEFAULT_PLAY_ON_GENERATE = False

# Max words per text chunk, applied to the source text in "STT flow"
MAX_WORDS_PER_SEGMENT_STT = 40

MENU_CLEARS_SCREEN = False

PAUSE_DURATION_WORD = 0.1
PAUSE_DURATION_PHRASE = 0.5
PAUSE_DURATION_SENTENCE = 0.9
PAUSE_DURATION_PARAGRAPH = 1.2
PAUSE_DURATION_SECTION = 2.0
PAUSE_DURATION_UNDEFINED = 1.0

REAL_TIME_BUFFER_MAX_SECONDS = 60 * 5

VOICE_TRANSCRIBE_MIN_PROBABILITY = 0.75 # Use 0.0 to skip probability filtering

