"""
Constants - config-like values
TODO: consider making this a config file proper
"""

import os

from tts_audiobook_tool.app_types import HighShelfEq, SegmentationStrategy
from tts_audiobook_tool.constants import MAX_WORDS_PER_SEGMENT_MAX

DEV = os.getenv("TTS_AUDIOBOOK_TOOL_DEV", "").lower() in ("true", "1", "yes") and True

PROJECT_DEFAULT_LANGUAGE = "en"
PROJECT_DEFAULT_BREAK_EFFECT = False
PROJECT_DEFAULT_REALTIME_SAVE = False
PROJECT_DEFAULT_CHAT_SAVE = False
PROJECT_DEFAULT_CHAT_SAVE_MIC = False
PROJECT_DEFAULT_LIMIT_SILENCE_GAPS = False
PROJECT_DEFAULT_GEN_AUTO_CONCAT = False
PROJECT_DEFAULT_STREAMING_CHAT = True
PROJECT_DEFAULT_SEGMENTATION_STRATEGY = SegmentationStrategy.SENTENCE_PLUS
PROJECT_DEFAULT_GENERATIVE_UPSAMPLING = False
PROJECT_DEFAULT_HIGH_SHELF_EQ = HighShelfEq.DISABLED
PROJECT_MAX_RETRIES_DEFAULT = 2
PROJECT_MAX_RETRIES_MIN = 0
PROJECT_MAX_RETRIES_MAX = 5
PROJECT_BATCH_SIZE_DEFAULT = 1
PROJECT_BATCH_SIZE_MAX = 99
PROJECT_CONCURRENT_REQUESTS_MAX = 16

PREFS_DEFAULT_PLAY_ON_GENERATE = False
CHAT_INPUT_MODE_MIC_IMMEDIATE = "mic_immediate"
CHAT_INPUT_MODE_MIC_ENTER = "mic_enter"
CHAT_INPUT_MODE_TEXT = "text"
CHAT_INPUT_MODES = (
    CHAT_INPUT_MODE_MIC_IMMEDIATE,
    CHAT_INPUT_MODE_MIC_ENTER,
    CHAT_INPUT_MODE_TEXT,
)
PREFS_DEFAULT_CHAT_INPUT_MODE = CHAT_INPUT_MODE_MIC_IMMEDIATE

# Max words per text chunk, applied to the source text in "STT flow"
MAX_WORDS_PER_SEGMENT_STT = 40

PAUSE_DURATION_WORD = 0.1
PAUSE_DURATION_PHRASE = 0.5
PAUSE_DURATION_SENTENCE = 0.9
PAUSE_DURATION_PARAGRAPH = 1.2
PAUSE_DURATION_SPACE_BREAK = 2.0
PAUSE_DURATION_SECTION = 2.5
PAUSE_DURATION_UNDEFINED = 1.0

PROJECT_DEFAULT_LIMIT_SILENCE_GAPS_DURATION = 1.0
SILENCE_GAP_DURATION_MIN = 0.0
SILENCE_GAP_DURATION_MAX = 2.0

REAL_TIME_BUFFER_MAX_SECONDS = 60 * 5

PRINT_FEEDBACK_PAUSE_CLEAR_SCREEN = 0.4
PRINT_FEEDBACK_PAUSE_NO_CLEAR_SCREEN = 0.8

CHAT_SILENCE_THRESHOLD_CHUNKED = 0.66
CHAT_SILENCE_THRESHOLD_IMMEDIATE = 1.0

# Use 0.0 to skip probability filtering
VOICE_CLONE_TRANSCRIBE_MIN_PROBABILITY = 0.75 

ROLLING_CONTINUATION_MAX_WORDS = MAX_WORDS_PER_SEGMENT_MAX * 2
