from tts_audiobook_tool.app_types import Hint
from tts_audiobook_tool.constants import *

HINT_LONG_PATHS = Hint(
    "long_paths",
    "It appears your system does not support long file paths",
    "App relies on pretty long filenames, so be sure to use\nshort directory paths when creating new projects"
)

HINT_OUTE_CONFIG = Hint(
    "oute_config",
    "This appears to be your first time running the application using the Oute TTS model",
    "As a reminder, you'll want to review and adjust the settings\nin the file \"config_oute.py\" for optimal performance."
)

HINT_TKINTER = Hint(
    "tkinter",
    "tkinter not installed",
    "Please install \"tkinter\" if you want OS file requestor functionality (It is not required, though)."
)

HINT_PROJECT_SUBDIRS = Hint(
    "project_subdirs",
    "Within your newly created project directory...",
f"""The {COL_ACCENT}segments{COL_DEFAULT} subdirectory contains the individual sound segments generated by the TTS model.
The {COL_ACCENT}combined{COL_DEFAULT} subdirectory contains the final, concatenated sound file/s ready for playing."""
)

HINT_LINE_BREAKS = Hint(
    "line_breaks",
    "Note:",
    "Line breaks are treated as paragraph delimiters.\nIf your source text uses manual line breaks for word wrapping\n(eg, Project Gutenberg), you will want to reformat it first."
)

HINT_MULTIPLE_MP3S = Hint(
    "multiple_mp3s",
    "Multiple MP3 files?",
    "If you want to combine multiple MP3 files in a directory,\nthis can be done from the Tools/Options menu"
)

HINT_OUTE_LOUD_NORM = Hint(
    "oute_loud_norm",
    "Tip",
    "Oute generations can have considerable variance in loudness.\nConsider using \"stronger.\""
)

HINT_FISH_S1_FIRST_COMPILE = Hint(
    "fish_first",
    "Please note...",
"""On the first inference, the Fish model may go through a compilation step
which may take a minute or two, with no feedback shown."""
)

HINT_FISH_S2_FIRST_COMPILE = Hint(
    "fish_s2_first",
    "Please note...",
"""On the first inference, the Fish model may go through a compilation step
which may take a minute or two, with no feedback shown."""
)

HINT_DOTS_FIRST_COMPILE = Hint(
    "dots_first",
    "Please note...",
"""On the first inference, the dots.tts model may go through a compilation step
which may take an extra minute or two."""
)

HINT_TEST_REAL_TIME = Hint(
    "test_real_time",
    "Tip",
f"""After setting voice clone or changing other model properties,
consider using \"{COL_ACCENT}Menu > Realtime playback{COL_DEFAULT}\" to quickly test audio
generation quality before committing to generating audiobook."""
)

HINT_SPEED_UP = Hint(
    "speed_up",
    "Note",
"""Use this feature to create a sped-up (or slowed-down) copy of a voice clone sample.
This can be potentially useful for modulating the speed of narration of the generated audio."""
)

HINT_INDEX_SAMPLE_LEN = Hint(
    "index_sample_len",
    "Note",
    """IndexTTS2 ignores voice sample audio data past the 15 second mark"""
)

HINT_STT_ENHANCE = Hint(
    "stt_enhance",
    "Text preparation...",
"""It's recommended to first remove any large chunks
from the source text that do not occur in the audio narration.
Common examples are: publisher information, table of contents, etc"""
)

HINT_STT_ENHANCE_CACHED = Hint(
    "stt_enhance_cached",
    "Transcription data is cached",
"""If you feel the need to modify the source text to minimize \"discontinuities\",
you can re-run the \"Enhance existing audiobook\" process, and it will run faster
the second time through, as the audio transcription data has been cached."""
)

HINT_LINUX_CUDNN_VERSION = Hint(
    "stt_linux_cudnn_version",
    f"{COL_ERROR}cuDNN version mismatch",
f"""The currently installed version of torch may be incompatible with faster-whisper for CUDA acceleration.
Either downgrade your version of torch (see README file), or change the Whisper
device to CPU ({COL_ACCENT}Options > Whisper config > CPU{COL_DEFAULT}).""")

HINT_MAX_WORDS_OVER_DEFAULT_MESSAGE = """The project's source text word count per segment (%1)
exceeds the application's recommended range for the current TTS model (%2).
Make sure this is what you want before generating audio."""

HINT_CHATTERBOX_PYTHON_DOWNGRADE = Hint(
    "chatterbox_python_downgrade",
    "The app's requirements for Chatterbox have changed",
"""To run the Chatterbox model, the app now requires a virtual environment running Python 3.11 (which is a downgrade).
Please re-install your Chatterbox-specific virtual environment using Python v3.11 by following the procedure described in the README.
You could also choose to roll back to a previous commit if you do not care about the most recent updates..."""
)

HINT_VALIDATION_UNSUPPORTED_LANGUAGE = Hint(
    "validation_unsupported_language",
    "Transcription validation will be disabled",
    "Transcription validation is unsupported for %1 and will be automatically disabled."
)

HINT_TRANSCRIPTION = Hint(
    "transcription",
    "Note",
"""The Whisper speech-to-text model is used to check the generated audio for errors.
Because it is used concurrently with the text-to-speech model, it can add 2-3 GB to
VRAM memory requirements."""
)

HINT_VOICE_TRANSCRIPT = Hint(
    "voice_transcript",
    "Voice clone transcript",
"""Because this TTS model requires a transcript of the voice clone sample,
the app will automatically transcribe the text using Whisper.
If a .txt file with the same base file name exists, it will use that instead."""
)

HINT_FORCED_STRICTNESS_LOW = Hint(
    "",
    "Note",
f"""Because language code is not en or es, the setting \"Word error tolerance\"
has been automatically set to \"Low\""""
)

HINT_TOLERANCE_FIRST_CLASS = Hint(
    "tolerance_first_class",
    "Note",
f"""The app has enhanced word error detection logic for language codes \"en\" and \"es\".
Consider setting \"Word error tolerance\" to Moderate or even Strict."""
)

HINT_SEED = Hint(
    "seed",
    "Note",
"""Setting a static seed value guarantees idempotent
audio generations when batching is not enabled.
Re-tried generations will always use a random seed."""
)

HINT_BATCH = Hint(
    "Batching",
    "Note",
"""When batching is active, lines will get processed slightly out of sequence
to maximize throughput. For projects with user-defined voice selections,
even more so."""
)

HINT_VIBEVOICE_LORA = Hint(
    "vibevoice_lora",
    "LoRA support is experimental",
"""Current tips:
- Train your LoRA using https://github.com/voicepowered-ai/VibeVoice-finetuning with parameter \"voice_prompt_drop_rate 1\"
- Avoid using a LoRA and a voice clone sample at the same time"""
)

HINT_DELETE_SEGMENTS = Hint(
    "delete_segments",
    "Tip",
"""Use this to selectively delete sound segments with poor or inaccurate output
(or, you can also just delete the files directly at: %1).
Afterwards, generate those items again as desired."""
)

HINT_LLM_CHAT = Hint(
    "llm_chat",
    "Tip",
"""Works best when:
(1) TTS model inferences faster than realtime, and
(2) LLM returns results quickly (eg, without reasoning enabled)"""
)

HINT_FULL_SCREEN_UI = Hint(
    "full_screen_ui",
    "Updated full-screen UI",
"""The app now relies on a full-screen menu UI, so the “Menu does not clear screen”
option has been removed. Menus will now always appear on a cleared screen."""
)

HINT_MOSS_REMOTE_CODE = Hint(
    "moss_remote_code",
    "Caution",
"""MOSS-TTS utilizes remotely downloaded code to operate:
%1
Be aware of the risks before continuing."""
)

HINT_MOSS_TEMPERATURE = Hint(
    "moss_temperature",
    "Note",
"""MOSS-TTS is susceptible to failing to properly terminate generations when
temperature is set too low. Use low values with caution..."""
)

HINT_SGL_OMNI_DORMANT = Hint(
    "sgl_omni_dormant",
    "Saved SGL-Omni settings are inactive in this venv",
"""You have SGL-Omni settings saved, but this virtual environment is not set up
for SGL-Omni, so they will not be used here.
SGL-Omni runs from the dedicated venv created by requirements-sgl-omni.txt
(see the README). Create or refresh that venv and run the app from it
to use your saved settings again."""
)

HINT_SGL_OMNI_URL = Hint(
    "sgl_omni_url",
    "Set the URL to your SGL Omni server",
    """No SGL-Omni server URL is set in your preferences, so the app
is assuming the server is running at the default address: http://localhost:8000
It doesn't appear to be online there, so set the correct URL in
"Options > SGL-Omni server URL" to point the app at your server."""
)

HINT_DIALOG_VOICE = Hint(
    "dialog_voice",
    "Dialog voices",
"""Because dialog segmentation was enabled for this import,
detected dialog lines have been assigned to voice 2.

To generate dialog using a different voice from the narrator/default:
(1) Make sure to add a second voice clone and
(2) Set Voice selection mode to User-defined."""
)