"""Non-runtime model capabilities shared by class-based and configured providers."""
from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from tts_audiobook_tool.app_types import ReadinessIssue, VoiceDisplayInfo
from tts_audiobook_tool.tts_models.tts_model_type import TtsModelSpec

if TYPE_CHECKING:
    from tts_audiobook_tool.project import Project


class ModelSupport(Protocol):
    INFO: TtsModelSpec

    def prepare_text_for_inference(self, project: Project, text: str, *, apply_word_substitutions: bool = True) -> str: ...
    def get_blocking_issues(self, project: Project, instance: object = None) -> list[ReadinessIssue]: ...
    def get_output_sample_rate(self, project: Project, instance: object = None) -> int: ...
    def get_menu_text(self, project: Project, instance: object = None) -> str: ...
    def get_voice_tag(self, project: Project) -> str: ...
    def get_voice_tag_for_value(self, value: str) -> str: ...
    def get_voice_display_info(self, project: Project, instance: object = None) -> VoiceDisplayInfo | None: ...
    def get_max_words_range_reco(self, project: Project, instance: object = None) -> tuple[int, int, str]: ...
    def should_trim_trailing_token_noise(self, project: Project, instance: object = None) -> bool: ...
    def can_hallucinate_music(self, project: Project, instance: object = None) -> bool: ...
