from .voice_menu_shared import VoiceMenuShared
from .voice_oute_menu import VoiceOuteMenu
from .voice_chatterbox_menu import VoiceChatterboxMenu
from .voice_fish_menu import VoiceFishMenu
from .voice_higgs_menu import VoiceHiggsMenu
from .voice_vibevoice_menu import VoiceVibeVoiceMenu
from .voice_indextts2_menu import VoiceIndexTts2Menu
from .voice_glm_menu import VoiceGlmMenu
from .voice_mira_menu import VoiceMiraMenu
from .voice_qwen3_menu import VoiceQwen3Menu
